//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuotaMensual
    {
        public long IDCuotaMensual { get; set; }
        public long IDAlquiler { get; set; }
        public Nullable<int> Monto { get; set; }
        public Nullable<System.DateTime> Periodo { get; set; }
        public string Pago { get; set; }
        public string FechaPago { get; set; }
        public Nullable<int> MontoRecargo { get; set; }
        public Nullable<int> MontoTotal { get; set; }
        public int Numero { get; set; }
    
        public virtual Alquiler Alquiler { get; set; }
    }
}
