//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edificio
    {
        public Edificio()
        {
            this.Propiedad = new HashSet<Propiedad>();
        }
    
        public long IDEdificio { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> MontoExpensas { get; set; }
        public long IDLocalidad { get; set; }
        public Nullable<long> IDBarrio { get; set; }
    
        public virtual ICollection<Propiedad> Propiedad { get; set; }
    }
}
