//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localidad
    {
        public Localidad()
        {
            this.Inquilino = new HashSet<Inquilino>();
            this.Garante = new HashSet<Garante>();
            this.Propietario = new HashSet<Propietario>();
            this.Barrio = new HashSet<Barrio>();
        }
    
        public long IDLocalidad { get; set; }
        public long IDProvincia { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CodigoPostal { get; set; }
    
        public virtual ICollection<Inquilino> Inquilino { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<Garante> Garante { get; set; }
        public virtual ICollection<Propietario> Propietario { get; set; }
        public virtual ICollection<Barrio> Barrio { get; set; }
    }
}
