//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDPropertyEntities : DbContext
    {
        public BDPropertyEntities()
            : base("name=BDPropertyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Alquiler> Alquiler { get; set; }
        public DbSet<CuotaMensual> CuotaMensual { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<Garante> Garante { get; set; }
        public DbSet<Inquilino> Inquilino { get; set; }
        public DbSet<Localidad> Localidad { get; set; }
        public DbSet<Propietario> Propietario { get; set; }
        public DbSet<Provincia> Provincia { get; set; }
        public DbSet<Tipo> Tipo { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Edificio> Edificio { get; set; }
        public DbSet<Barrio> Barrio { get; set; }
        public DbSet<Propiedad> Propiedad { get; set; }
    }
}
