//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propiedad
    {
        public Propiedad()
        {
            this.Alquiler = new HashSet<Alquiler>();
        }
    
        public long IDPropiedad { get; set; }
        public long IDPropietario { get; set; }
        public Nullable<long> IDBarrio { get; set; }
        public long IDTipo { get; set; }
        public long IDEstado { get; set; }
        public Nullable<long> IDEdificio { get; set; }
        public long IDLocalidad { get; set; }
        public string Direccion { get; set; }
        public string Tamaño { get; set; }
        public string CantBaños { get; set; }
        public string Patio { get; set; }
        public string Cochera { get; set; }
        public string Garage { get; set; }
        public string Cocina { get; set; }
        public string Comedor { get; set; }
        public string VistaCalle { get; set; }
        public string GasNatural { get; set; }
        public string Pileta { get; set; }
        public string Asador { get; set; }
        public string PisoNro { get; set; }
        public string CantHabitac { get; set; }
    
        public virtual ICollection<Alquiler> Alquiler { get; set; }
        public virtual Barrio Barrio { get; set; }
        public virtual Edificio Edificio { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Propietario Propietario { get; set; }
        public virtual Tipo Tipo { get; set; }
    }
}
