//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propietario
    {
        public Propietario()
        {
            this.Propiedad = new HashSet<Propiedad>();
        }
    
        public long IDPropietario { get; set; }
        public long IDLocalidad { get; set; }
        public string NombreYApellido { get; set; }
        public string DNI { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public Nullable<long> Telefono { get; set; }
        public string CorreoElectronico { get; set; }
        public string Direccion { get; set; }
    
        public virtual Localidad Localidad { get; set; }
        public virtual ICollection<Propiedad> Propiedad { get; set; }
    }
}
